#!/bin/bash 

# File: install-dokuwiki
#
# Purpose: Script that will create a new GCE instance and install a secure Dokuwiki service
#
# Requirements:
#  Run within a working GCP SDK project
#


# Ingest environment variables
source gcp-context

# Inject changes
sed -i .foo "s/ADMIN_USER/${WIKI_ADMIN_USER}/g"     nginx-config
sed -i .foo "s/SERVER_DOMAIN_NAME/${DOMAIN_NAME}/g" nginx-config


#gcloud compute instances create ${GCE_NAME} --machine-type f1-micro --zone ${GCE_ZONE}

#gcloud compute copy-files remote-setup ${WIKI_ADMIN_USER}@${GCE_NAME}:~/remote-setup

#gcloud compute ssh ${WIKI_ADMIN_USER}@${GCE_NAME}:~/remote-setup

echo ${GCE_NAME}

cat nginx-config